export const queryKeys = {
  auth: {
    all: ['auth'] as const,
    profile: () => ['auth', 'profile'] as const,
  },
  users: {
    all: ['users'] as const,
    lists: () => ['users', 'list'] as const,
    list: (params?: object) => ['users', 'list', params] as const,
    detail: (id: string) => ['users', 'detail', id] as const,
    systemStats: () => ['users', 'system-stats'] as const,
  },
  departments: {
    all: ['departments'] as const,
    lists: () => ['departments', 'list'] as const,
    list: (params?: object) => ['departments', 'list', params] as const,
    detail: (id: string) => ['departments', 'detail', id] as const,
  },
  employees: {
    all: ['employees'] as const,
    lists: () => ['employees', 'list'] as const,
    list: (params?: object) => ['employees', 'list', params] as const,
    detail: (id: string) => ['employees', 'detail', id] as const,
    stats: () => ['employees', 'stats'] as const,
    salaryGrades: () => ['employees', 'salary-grades'] as const,
  },
  attendance: {
    all: ['attendance'] as const,
    lists: () => ['attendance', 'list'] as const,
    list: (params?: object) => ['attendance', 'list', params] as const,
    summary: (params?: object) => ['attendance', 'summary', params] as const,
    monthly: (employeeId: string) => ['attendance', 'monthly', employeeId] as const,
  },
  leave: {
    all: ['leave'] as const,
    types: () => ['leave', 'types'] as const,
    requests: (params?: object) => ['leave', 'requests', params] as const,
    balances: (employeeId: string) => ['leave', 'balances', employeeId] as const,
  },
  payroll: {
    all: ['payroll'] as const,
    runs: () => ['payroll', 'runs'] as const,
    run: (id: string) => ['payroll', 'run', id] as const,
    deductions: () => ['payroll', 'deductions'] as const,
    payslip: (id: string) => ['payroll', 'payslip', id] as const,
    employeePayslips: (employeeId: string) => ['payroll', 'employee-payslips', employeeId] as const,
  },
  accounts: {
    all: ['accounts'] as const,
    lists: () => ['accounts', 'list'] as const,
    list: (params?: object) => ['accounts', 'list', params] as const,
    detail: (id: string) => ['accounts', 'detail', id] as const,
    trialBalance: (params?: object) => ['accounts', 'trial-balance', params] as const,
    ledger: (id: string) => ['accounts', 'ledger', id] as const,
  },
  journalEntries: {
    all: ['journal-entries'] as const,
    lists: () => ['journal-entries', 'list'] as const,
    list: (params?: object) => ['journal-entries', 'list', params] as const,
    detail: (id: string) => ['journal-entries', 'detail', id] as const,
    fiscalYears: () => ['journal-entries', 'fiscal-years'] as const,
  },
  bankReconciliation: {
    all: ['bank'] as const,
    accounts: () => ['bank', 'accounts'] as const,
    account: (id: string) => ['bank', 'account', id] as const,
    statements: (bankAccountId: string) => ['bank', 'statements', bankAccountId] as const,
    statement: (id: string) => ['bank', 'statement', id] as const,
  },
  budgets: {
    all: ['budgets'] as const,
    lists: () => ['budgets', 'list'] as const,
    list: (params?: object) => ['budgets', 'list', params] as const,
    detail: (id: string) => ['budgets', 'detail', id] as const,
    variance: (id: string) => ['budgets', 'variance', id] as const,
  },
  clients: {
    all: ['clients'] as const,
    lists: () => ['clients', 'list'] as const,
    list: (params?: object) => ['clients', 'list', params] as const,
    detail: (id: string) => ['clients', 'detail', id] as const,
  },
  invoices: {
    all: ['invoices'] as const,
    lists: () => ['invoices', 'list'] as const,
    list: (params?: object) => ['invoices', 'list', params] as const,
    detail: (id: string) => ['invoices', 'detail', id] as const,
    stats: () => ['invoices', 'stats'] as const,
  },
  receivables: {
    all: ['receivables'] as const,
    lists: () => ['receivables', 'list'] as const,
    list: (params?: object) => ['receivables', 'list', params] as const,
    agingReport: () => ['receivables', 'aging-report'] as const,
  },
  revenue: {
    all: ['revenue'] as const,
    incomeSources: () => ['revenue', 'income-sources'] as const,
    entries: (params?: object) => ['revenue', 'entries', params] as const,
    stats: () => ['revenue', 'stats'] as const,
    recurring: () => ['revenue', 'recurring'] as const,
    recurringDue: () => ['revenue', 'recurring-due'] as const,
    adjustments: (params?: object) => ['revenue', 'adjustments', params] as const,
    adjustmentSummary: () => ['revenue', 'adjustment-summary'] as const,
  },
  pricing: {
    all: ['pricing'] as const,
    models: () => ['pricing', 'models'] as const,
    model: (id: string) => ['pricing', 'model', id] as const,
    discounts: () => ['pricing', 'discounts'] as const,
    commissions: () => ['pricing', 'commissions'] as const,
  },
  reports: {
    all: ['reports'] as const,
    financialSummary: () => ['reports', 'financial-summary'] as const,
    trialBalance: (params?: object) => ['reports', 'trial-balance', params] as const,
    incomeStatement: (params: object) => ['reports', 'income-statement', params] as const,
    balanceSheet: (params?: object) => ['reports', 'balance-sheet', params] as const,
    cashFlow: (params: object) => ['reports', 'cash-flow', params] as const,
  },
  announcements: {
    all: ['announcements'] as const,
    list: (params?: object) => ['announcements', 'list', params] as const,
    detail: (id: string) => ['announcements', 'detail', id] as const,
  },
  activityLogs: {
    all: ['activity-logs'] as const,
    list: (params?: object) => ['activity-logs', 'list', params] as const,
    stats: () => ['activity-logs', 'stats'] as const,
  },
};
